/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lab.pkg3.videojuego;

import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Cristian
 */
public class game_over extends javax.swing.JFrame {

    int puntos_valor;
    String nom_jugador;
    List<String> todos_los_ganadores = new ArrayList<>();
    
    public game_over() {
        initComponents();
        salir.setContentAreaFilled(false);
        salir.setBorderPainted(false);
        regresar.setContentAreaFilled(false);
        regresar.setBorderPainted(false);
        //mensaje_game_over.setForeground(new java.awt.Color(255, 255, 255));
        //mensaje_game_over.setFont(new java.awt.Font("Tahoma", 0, 24));
        puntos.setForeground(new java.awt.Color(255, 255, 255));
        puntos.setFont(new java.awt.Font("Tahoma", 0, 24));
        juegador.setForeground(new java.awt.Color(255, 255, 255));
        juegador.setFont(new java.awt.Font("Tahoma", 0, 24));
        lista_ganadores.setForeground(new java.awt.Color(255, 255, 255));
        lista_ganadores.setFont(new java.awt.Font("Tahoma", 0, 12));
        lista_ganadores.setBackground(new java.awt.Color(51, 102, 255));
        lista_ganadores.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        lista_ganadores.setGridColor(new java.awt.Color(255, 255, 255));
        lista_ganadores.setRowHeight(20);
        lista_ganadores.setRowMargin(2);
        lista_ganadores.setSelectionBackground(new java.awt.Color(51, 102, 255));
        lista_ganadores.setSelectionForeground(new java.awt.Color(255, 255, 255));
        lista_ganadores.setShowGrid(true);
        lista_ganadores.setShowVerticalLines(false);
        lista_ganadores.getTableHeader().setReorderingAllowed(false);
        lista_ganadores.setUpdateSelectionOnSort(false);
        lista_ganadores.setVerifyInputWhenFocusTarget(false);
        

    }
    
    public void mostrar_info(){
        DefaultTableModel mt = new DefaultTableModel();

        this.juegador.setText(nom_jugador);
        this.puntos.setText(Integer.toString(puntos_valor));
        guardar_ganadores g = new guardar_ganadores(nom_jugador, puntos_valor);
        g.guardar_jugador_archivo();
        todos_los_ganadores = guardar_ganadores.leer_archivo();
        List<String> temp = new ArrayList<>();
        List<String> temp2 = new ArrayList<>();
        for (int i = 0; i < todos_los_ganadores.size(); i++) {
            temp.add(todos_los_ganadores.get(i).split(",")[0]);
            temp2.add(todos_los_ganadores.get(i).split(",")[1]);
        }
        Object colums [] = {"Jugador", "Puntos"};
        mt.setColumnIdentifiers(colums);

        String data [][] = new String [todos_los_ganadores.size()][2];
        for (int i = 0; i < todos_los_ganadores.size(); i++) {
            data[i][0] = temp.get(i);
            data[i][1] = temp2.get(i);
            mt.addRow(new Object[]{data[i][0], data[i][1]});
        }
        
        lista_ganadores.setModel(mt);
       // if (puntos_valor == 10) {mensaje_game_over.setText("Felicidades ganastes");}
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        puntos = new javax.swing.JLabel();
        Points = new javax.swing.JLabel();
        juegador = new javax.swing.JLabel();
        salir = new javax.swing.JButton();
        regresar = new javax.swing.JButton();
        panel = new javax.swing.JScrollPane();
        lista_ganadores = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        puntos.setText("d");
        getContentPane().add(puntos);
        puntos.setBounds(110, 300, 30, 30);

        Points.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lab/pkg3/videojuego/imagenes/points.png"))); // NOI18N
        getContentPane().add(Points);
        Points.setBounds(92, 230, 50, 60);

        juegador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lab/pkg3/videojuego/imagenes/nice try (1).png"))); // NOI18N
        getContentPane().add(juegador);
        juegador.setBounds(50, 90, 140, 120);

        salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lab/pkg3/videojuego/imagenes/salida boton (1).png"))); // NOI18N
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        getContentPane().add(salir);
        salir.setBounds(290, 370, 50, 60);

        regresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lab/pkg3/videojuego/imagenes/restart2.png"))); // NOI18N
        regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresarActionPerformed(evt);
            }
        });
        getContentPane().add(regresar);
        regresar.setBounds(200, 370, 60, 60);

        lista_ganadores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        panel.setViewportView(lista_ganadores);

        getContentPane().add(panel);
        panel.setBounds(240, 100, 240, 250);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lab/pkg3/videojuego/imagenes/Pantalla score.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 500, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void regresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresarActionPerformed
        inicio i = new inicio();
        i.setVisible(true);
        this.setVisible(false);
        i.setBounds(0,0,500,500);
        i.setLocationRelativeTo(null);
    }//GEN-LAST:event_regresarActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_salirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(game_over.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(game_over.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(game_over.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(game_over.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new game_over().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Points;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel juegador;
    private javax.swing.JTable lista_ganadores;
    private javax.swing.JScrollPane panel;
    private javax.swing.JLabel puntos;
    private javax.swing.JButton regresar;
    private javax.swing.JButton salir;
    // End of variables declaration//GEN-END:variables
}
