/*
 * 
 */
package lab.pkg3.videojuego;
import java.applet.AudioClip;
import java.awt.Color;
import java.awt.Font;
import static javax.swing.SwingConstants.CENTER;

/**
 *
 * @author Cristian
 */
public class inicio extends javax.swing.JFrame {

    String jugador;

    public inicio(){
        //new MediaPlayer(new Media());
        initComponents();
        this.setLocationRelativeTo(null);
        jLabel2.setForeground(Color.WHITE);
        jLabel2.setFont(new Font("Arial", Font.BOLD, 12));
        nombre_jugador.setHorizontalAlignment(CENTER);
        Play.setContentAreaFilled(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nombre_jugador = new javax.swing.JTextField();
        Play = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        Fondop = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setSize(new java.awt.Dimension(500, 500));
        addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                formPropertyChange(evt);
            }
        });
        getContentPane().setLayout(null);

        nombre_jugador.setBackground(new java.awt.Color(51, 102, 255));
        nombre_jugador.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        nombre_jugador.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(nombre_jugador);
        nombre_jugador.setBounds(250, 40, 207, 34);

        Play.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lab/pkg3/videojuego/imagenes/JUGAR_r (1)_1.png"))); // NOI18N
        Play.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Play.setBorderPainted(false);
        Play.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PlayMouseClicked(evt);
            }
        });
        Play.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playActionPerformed(evt);
            }
        });
        getContentPane().add(Play);
        Play.setBounds(200, 410, 130, 50);

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Ingrese el nombre del jugador");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 40, 200, 34);

        Fondop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lab/pkg3/videojuego/imagenes/Pregunta2.png"))); // NOI18N
        getContentPane().add(Fondop);
        Fondop.setBounds(0, 0, 500, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void playActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playActionPerformed
        if (!nombre_jugador.getText().isEmpty()){
            AudioClip sonido;
            sonido = java.applet.Applet.newAudioClip(getClass().getResource("/Sonidos/sonidoinicio.wav"));
            sonido.stop();
            AudioClip timer;
            timer = java.applet.Applet.newAudioClip(getClass().getResource("/Sonidos/timer.wav"));
            timer.play();
            this.setVisible(false);
            jugador = nombre_jugador.getText();
            interfaz juego = new interfaz();
            juego.jugador = jugador;
            juego.setVisible(true);
            juego.setLocationRelativeTo(null);
            //juego.setBounds(50, 50, 800, 412);
            juego.setTitle("Pregunta 2");
        }
        


    }//GEN-LAST:event_playActionPerformed

    private void formPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_formPropertyChange
            AudioClip sonido;
            sonido = java.applet.Applet.newAudioClip(getClass().getResource("/Sonidos/sonidoinicio.wav"));
            sonido.play();
    }//GEN-LAST:event_formPropertyChange

    private void PlayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PlayMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_PlayMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new inicio().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fondop;
    public javax.swing.JButton Play;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField nombre_jugador;
    // End of variables declaration//GEN-END:variables

}
